
describe('advance concepts', () => {
  test.todo('scope')
  test.todo('context and the "this" keyword')
  test.todo('object reference')
  test.todo('prototype chain')
  test.todo('immutability vs mutability')
  test.todo('composition vs inheritance')
  test.todo('SOLID principles')
  test.todo('YAGNI KISS AHA')
  test.todo('state management')
  test.todo('dates')
  test.todo('new JS ?? .?')
  test.todo('Modulo operation')
  test.todo('truthy / falsy')
  test.todo('asyc await')
  test.todo('using npm packages')
  test.todo('front end frameworks React / Vue')
  test.todo('HTTP')
  test.todo('http REST service')
  test.todo('databases: SQL vs NOSQL')
  test.todo('unit tests vs functional / integration tests')
  test.todo('ddd architecture') // big bucks time!
})