
describe('advance concepts', () => {
  test.todo('block {} scope')
  test.todo('flat map')
  test.todo('context and the "this" keyword')
  test.todo('object reference')
  test.todo('prototype chain')
  test.todo('immutability vs mutability')
  test.todo('composition vs inheritance')
  test.todo('SOLID principles')
  test.todo('YAGNI KISS AHA')
  test.todo('state management')
  test.todo('dates')
  test.todo('new JS ?? .?')
  test.todo('Modulo operation')
  test.todo('truthy / falsy')
  test.todo('async await')
  test.todo('generators')
  test.todo('web components')
  test.todo('shadow dom')
  test.todo('spread operators')
  test.todo('Map and Set')
  test.todo('template literals')
  test.todo('"in" keyword')
  test.todo('block labels')
  test.todo('break / continue')
  test.todo('object.freeze')
  test.todo('js `math` binary math ')
  test.todo('currying / partials')
  test.todo('debugging code')
  test.todo('typescript basics')
  test.todo('using npm packages')
  test.todo('setting up a project')
  test.todo('front end frameworks React / Vue')
  test.todo('HTTP')
  test.todo('http REST service')
  test.todo('databases: SQL vs NOSQL')
  test.todo('unit tests vs functional / integration tests')
  test.todo('ddd architecture') // big bucks time!
  test.todo('dynamic modules')
  test.todo('defer / async load')
})