describe('numbers', () => {
  it.todo('import a module "myNumberFuncs"')
  it.todo('functions doing basic math')
  it.todo('function that calculates tip')
  it.todo('parseInt')
  it.todo('parseFloat')
  it.todo('toPrecision')
  it.todo('Number primitive')
  it.todo('use of Math functions "random number"')
  it.todo('not a number')
})